# tests sur plusieurs OS

ubuntu:default:
  image: "ubuntu:latest"
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential gfortran qt4-qmake libqt4-dev
  script:
    - qmake-qt4
    - make
    - ulimit -s unlimited; cd tests; ./tests
  only:
    - master
  tags:
    - tag1

ubuntu:fftw:
  image: "ubuntu:latest"
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential gfortran qt4-qmake libqt4-dev fftw*
  script:
    - qmake-qt4 "CONFIG+=fftw"
    - make
    - ulimit -s unlimited; cd tests; ./tests
  only:
    - master
  tags:
    - tag1

ubuntu:hdf5:
  image: "ubuntu:latest"
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential gfortran qt4-qmake libqt4-dev fftw* libhdf5-dev
  script:
    - qmake-qt4 "CONFIG+=fftw hdf5"
    - make
    - ulimit -s unlimited; cd tests; ./tests
  only:
    - master
  tags:
    - tag1

fedora:29:
  image: "fedora:29"
  before_script:
    - yum groupinstall -y "Development Tools" && yum install -y gcc-gfortran qt-devel
  script:
    - qmake-qt4
    - make
    - ulimit -s unlimited; cd tests; ./tests
  only:
    - master
  tags:
    - tag1

fedora:fftw:
  image: "fedora:29"
  before_script:
    - yum groupinstall -y "Development Tools" && yum install -y gcc-gfortran qt-devel fftw*
  script:
    - qmake-qt4 "CONFIG+=fftw"
    - make
    - ulimit -s unlimited; cd tests; ./tests
  only:
    - master
  tags:
    - tag1

fedora:hdf5:
  image: "fedora:29"
  before_script:
    - yum groupinstall -y "Development Tools" && yum install -y gcc-gfortran qt-devel fftw* hdf hdf5 hdf5-static hdf5-devel
  script:
    - qmake-qt4 "CONFIG+=fftw hdf5"
    - make
    - ulimit -s unlimited; cd tests; ./tests
  only:
    - master
  tags:
    - tag1

